@baseUrl = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3VwZXJhZG1pbiIsImVudGl0eVR5cGUiOiJtYXRyaXoiLCJlbnRpdHlJZCI6Im1hdHJpeiIsImlhdCI6MTc3NzcyMDg2MSwiZXhwIjoxNzc3NzQ5NjYxLCJzdWIiOiI0NWJkMThhNi0wMjAyLTRlNWYtOTlkMi01NzYwMWNkMjM5YmUifQ.P18c7m7H51UyKw48gJoOJXmhyD08O_zjW2XYb0IY2iU

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "admin@redetrade.com.br",
  "senha": "Admin@123456"
}

### Renovar token (usa refreshToken do cookie)
POST {{baseUrl}}/auth/refresh

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{token}}

### Meu perfil
GET {{baseUrl}}/auth/me
Authorization: Bearer {{token}}
